spring.application.name=constitution-awareness

# ===============================
# MySQL Database Configuration
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3306/constitution_awareness
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ===============================
# JPA / Hibernate
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Server
# ===============================

server.port=8080